apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-probe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-probe
  template:
    metadata:
      labels:
        app: multi-probe
    spec:
      containers:
      # HTTP GET Probe Container
      - name: nginx-http
        image: nginx:1.25
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

      # TCP Socket Probe Container
      - name: nginx-tcp
        image: nginx:1.25
        ports:
        - containerPort: 81
        livenessProbe:
          tcpSocket:
            port: 81
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 81
          initialDelaySeconds: 5
          periodSeconds: 5

      # Exec Command Probe Container
      - name: ubuntu-exec
        image: ubuntu
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/ready
          initialDelaySeconds: 5
          periodSeconds: 5
