apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-probe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-probe
  template:
    metadata:
      labels:
        app: tcp-probe
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
