apiVersion: apps/v1
kind: Deployment
metadata:
  name: exec-probe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exec-probe
  template:
    metadata:
      labels:
        app: exec-probe
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/ready
          initialDelaySeconds: 3
          periodSeconds: 5
