apiVersion: apps/v1
kind: Deployment
metadata:
  name: tolerant-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tolerant-app
  template:
    metadata:
      labels:
        app: tolerant-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
      tolerations:
      - key: "env"
        operator: "Equal"
        value: "prod"
        effect: "NoSchedule"
