# Use official Python base image
FROM python:3.12.7-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into /app in the container
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port Flask runs on
EXPOSE 5000

# Run the application
CMD ["python", "app.py"]
